version: "3.8"

volumes:
  plast-db:
    driver: local
  plast-web-nginx:
    driver: local
  plast-web-certificates:
    driver: local

services:
  db:
    image: postgres:13
    volumes:
      - plast-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  app:
    image: gcr.io/plant-helper/backend
    pull_policy: always
    build: ./app
    command: /usr/src/app/docker-entrypoint.sh
    depends_on:
      - db
    environment:
      - HOST=${HOST}
      - EMAIL_ACCOUNT=${EMAIL_ACCOUNT}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - VAPID_PRIVATE=${VAPID_PRIVATE}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}

  web:
    image: gcr.io/plant-helper/web
    pull_policy: always
    volumes:
      - plast-web-nginx:/etc/nginx
      - plast-web-certificates:/etc/letsencrypt
    build:
      context: ./plants-shelves
      dockerfile: Dockerfile-prod
    ports:
      - "80:80"
      - "443:443"
    links:
      - app