version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  app:
    image: gcr.io/plant-helper/backend
    build: ./app
    command: python manage.py runserver ${HOST}:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - FE_HOST=localhost

  web:
    image: gcr.io/plant-helper/web
    build:
      context: ./plants-shelves
      dockerfile: Dockerfile-prod
    command: npm start
    ports:
      - "443:3000"
    depends_on:
      - db
    environment:
      - HTTPS=true
      - REACT_APP_GQL_HOST=localhost
