version: "3.8"

volumes:
  plast-db:
    driver: local

services:
  db:
    image: postgres
    volumes:
      - plast-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  app:
    image: gcr.io/plant-helper/backend
    build: ./app
    command: /usr/src/app/docker-entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - FE_HOST=${HOST}

  web:
    image: gcr.io/plant-helper/web
    build:
      context: ./plants-shelves
      dockerfile: Dockerfile-prod
    command: serve /app -c /app/serve.json
    ports:
      - "80:5000"
    depends_on:
      - db
    environment:
      - HTTPS=true
      - REACT_APP_GQL_HOST=${HOST}
