version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  app:
    build: ./app
    command: /usr/src/app/docker-entrypoint.sh
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - HOST=0.0.0.0
  web:
    build: ./plants-shelves
    command: npm start
    volumes:
      - ./plants-shelves:/app
    ports:
      - "3000:3000"
    depends_on:
      - db