version: "3.9"

volumes:
  plast-db:
    driver: local

services:
  db:
    image: postgres:13
    volumes:
      - plast-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  app:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - HOST=${HOST}
      - EMAIL_ACCOUNT=${EMAIL_ACCOUNT}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
  web:
    build: ./plants-shelves
    command: npm start
    volumes:
      - ./plants-shelves:/app
    ports:
      - "80:3000"
    depends_on:
      - app
    environment:
      - NODE_ENV="production"