version: "3.9"

volumes:
  plast-db:
    driver: local

services:
  db:
    image: postgres
    volumes:
      - plast-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  app:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  web:
    build: ./plants-shelves
    command: npm start
    volumes:
      - ./plants-shelves:/app
    ports:
      - "80:3000"
    depends_on:
      - db