# Generated by Django 3.2 on 2021-06-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddIndex(
            model_name='plantentry',
            index=models.Index(fields=['nick_name'], name='catalog_pla_nick_na_b1b0f4_idx'),
        ),
    ]
