# Generated by Django 3.2 on 2021-09-18 18:22

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantentry',
            name='days_between_watering_dormant',
            field=models.DurationField(default=datetime.timedelta(days=10)),
        ),
        migrations.AddField(
            model_name='plantentry',
            name='days_between_watering_growing',
            field=models.DurationField(default=datetime.timedelta(days=5)),
        ),
        migrations.AddField(
            model_name='plantentry',
            name='nick_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), null=True, size=None),
        ),
        migrations.AddIndex(
            model_name='plantentry',
            index=models.Index(fields=['scientific_name'], name='catalog_pla_scienti_6cff17_idx'),
        ),
    ]
