# Generated by Django 3.2 on 2021-09-28 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_nickname'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='nickname',
            index=models.Index(fields=['name'], name='catalog_nic_name_4ef92b_idx'),
        ),
    ]
