# Generated by Django 3.2 on 2025-02-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_nickname_catalog_nic_name_4ef92b_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantentry',
            name='image_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
