# Generated by Django 3.2 on 2022-10-20 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20211216_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedWith',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_from', to=settings.AUTH_USER_MODEL)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrowed_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
