# pull official base image
FROM node:16.1.0-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
COPY . ./
RUN npm install --silent
RUN npm install react-scripts -g --silent
RUN npm run build

# add app
COPY ./build ./build


FROM node:16.1.0-slim
WORKDIR /app

RUN npm install -g serve

COPY --from=0 /app/build ./
# start app
CMD ["serve", "-s build", "-l 433"]