# Generated by Django 3.2 on 2021-04-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_time_between_watering'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='plant',
            name='furtilized',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='planted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='repoted',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watered',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
