# Generated by Django 3.2 on 2021-05-02 16:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_auto_20210429_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='furtilized',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='plant',
            name='planted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='plant',
            name='repoted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
