# Generated by Django 3.2 on 2021-08-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0008_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='user_wide_id',
            field=models.IntegerField(default=1),
        ),
    ]
