# Generated by Django 3.2 on 2021-08-24 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0009_alter_symbol_user_wide_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symbol',
            name='plant',
        ),
        migrations.RemoveField(
            model_name='symbol',
            name='user',
        ),
        migrations.AddField(
            model_name='plant',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.symbol'),
        ),
    ]
