# Generated by Django 3.2 on 2021-08-24 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0011_symbol_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='symbol',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='plants.symbol'),
        ),
    ]
