# Generated by Django 3.2 on 2021-09-29 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0014_wateredatentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='time_between_watering',
            new_name='time_between_watering_growing',
        ),
        migrations.AddField(
            model_name='plant',
            name='time_between_watering_dormant',
            field=models.DurationField(default=datetime.timedelta(days=10)),
        ),
    ]
