# Generated by Django 3.2 on 2021-11-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0015_auto_20210929_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='color_background',
            field=models.CharField(default='#000000', max_length=9),
        ),
        migrations.AddField(
            model_name='room',
            name='color_text',
            field=models.CharField(default='#FFFFFF', max_length=9),
        ),
    ]
