# Generated by Django 3.2 on 2021-06-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NamePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddIndex(
            model_name='namepart',
            index=models.Index(fields=['name'], name='names_namep_name_82229b_idx'),
        ),
    ]
